In [1]:
pip install -U scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install qiskit_algorithms

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install qiskit_machine_learning

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
%matplotlib inline

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df_iris = pd.read_csv('iris.csv')

In [7]:
iris_data = pd.DataFrame(df_iris, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])
iris_target = pd.DataFrame(df_iris, columns=['Species'])

In [12]:
print(df_iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [8]:
x = iris_data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_target[["Species"]]
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)
C = 1.0
csvm_model = SVC()
csvm_model.fit(x_train.values, y_train.values.ravel())
csvm_pred = csvm_model.predict(x_test.values)
print("Confusion Matrix")
print(confusion_matrix(y_test, csvm_pred))
print("Classification Report")
print(classification_report(y_test, csvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
csvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[14  0  0]
 [ 0 17  2]
 [ 0  1 11]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      0.89      0.92        19
 Iris-virginica       0.85      0.92      0.88        12

       accuracy                           0.93        45
      macro avg       0.93      0.94      0.93        45
   weighted avg       0.94      0.93      0.93        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-virginica'], dtype=object)

In [39]:
x = iris_data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_target[["Species"]]
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)
C = 1.0
csvm_model = SVC()
csvm_model.fit(x_train.values, y_train.values.ravel())
csvm_pred = csvm_model.predict(x_test.values)
print("Confusion Matrix")
print(confusion_matrix(y_test, csvm_pred))
print("Classification Report")
print(classification_report(y_test, csvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
csvm_model.predict([[5.1,3.5,1.4,0.2]])

Confusion Matrix
[[12  0  0]
 [ 0 11  0]
 [ 0  5 17]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.69      1.00      0.81        11
 Iris-virginica       1.00      0.77      0.87        22

       accuracy                           0.89        45
      macro avg       0.90      0.92      0.90        45
   weighted avg       0.92      0.89      0.89        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-setosa'], dtype=object)

In [17]:
y_train.values.ravel()

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-vi

In [9]:
from qiskit.circuit.library import ZZFeatureMap
from qiskit.primitives import Sampler
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_machine_learning.kernels import FidelityQuantumKernel
adhoc_dimension=2
adhoc_feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, reps=2, entanglement="linear") 
#classical data is encoded into qubit angles
sampler = Sampler()
fidelity = ComputeUncompute(sampler=sampler)
adhoc_kernel = FidelityQuantumKernel(fidelity=fidelity, feature_map=adhoc_feature_map)

In [33]:
dir(adhoc_feature_map)

['__abstractmethods__',
 '__and__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '__xor__',
 '_abc_impl',
 '_alpha',
 '_ancillas',
 '_append',
 '_appended_blocks',
 '_appended_entanglement',
 '_base_name',
 '_bounds',
 '_build',
 '_build_additional_layers',
 '_build_entanglement_layer',
 '_build_rotation_layer',
 '_builder_api',
 '_calibrations',
 '_check_configuration',
 '_check_dups',
 '_clbit_indices',
 '_control_flow_scopes',
 '_convert_to_block',
 '_create_creg',
 '_create_qreg',
 '_cregs',
 '_current_scope',
 '_data',
 '_data_map_func',
 '_en

In [34]:
adhoc_feature_map.pauli

<bound method QuantumCircuit.pauli of <qiskit.circuit.library.data_preparation.zz_feature_map.ZZFeatureMap object at 0x000002A2CBE1B310>>

In [31]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel=adhoc_kernel)
qsvm_model.fit(x_train, y_train.values.ravel())
qsvm_pred = qsvm_model.predict(x_test)
print("Confusion Matrix")
print(confusion_matrix(y_test, qsvm_pred))
print("Classification Report")
print(classification_report(y_test, qsvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
qsvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[11  1  2]
 [ 1 14  4]
 [ 2  1  9]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       0.79      0.79      0.79        14
Iris-versicolor       0.88      0.74      0.80        19
 Iris-virginica       0.60      0.75      0.67        12

       accuracy                           0.76        45
      macro avg       0.75      0.76      0.75        45
   weighted avg       0.77      0.76      0.76        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-versicolor'], dtype=object)

In [41]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel=adhoc_kernel)
qsvm_model.fit(x_train, y_train.values.ravel())
qsvm_pred = qsvm_model.predict(x_test)
print("Confusion Matrix")
print(confusion_matrix(y_test, qsvm_pred))
print("Classification Report")
print(classification_report(y_test, qsvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
qsvm_model.predict([[5.1,3.5,1.4,0.2]])

Confusion Matrix
[[11  1  0]
 [ 0 10  1]
 [ 3  6 13]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       0.79      0.92      0.85        12
Iris-versicolor       0.59      0.91      0.71        11
 Iris-virginica       0.93      0.59      0.72        22

       accuracy                           0.76        45
      macro avg       0.77      0.81      0.76        45
   weighted avg       0.81      0.76      0.75        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-setosa'], dtype=object)